// <auto-generated />
using System;
using Duthie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duthie.Bot.Migrations.Sqlite
{
    [DbContext(typeof(DuthieDbContext))]
    [Migration("20220603174630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Duthie.Types.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HomeTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Overtime")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Shootout")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisitorScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VisitorTeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.GuildAdmin", b =>
                {
                    b.Property<string>("GuildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "MemberId");

                    b.ToTable("GuildAdmins", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.GuildMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMessages", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Guilds.Guild", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Leagues.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SiteId", "Name")
                        .IsUnique();

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Leagues.LeagueTeam", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InternalId");

                    b.HasKey("LeagueId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("LeagueTeams", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1da163da-3070-4a24-97ee-de76fa506419"),
                            Name = "Anaheim Ducks",
                            ShortName = "Ducks",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d848e8aa-a7c4-4393-9b6b-98cbaa2bd632"),
                            Name = "Arizona Coyotes",
                            ShortName = "Coyotes",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("49fa5713-8a30-4682-9ff3-ce60aa3cbb42"),
                            Name = "Boston Bruins",
                            ShortName = "Bruins",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c11a41ff-6fb0-44f9-8e1e-a058eb00b98f"),
                            Name = "Buffalo Sabres",
                            ShortName = "Sabres",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("95abc7c0-74c3-4bcb-8368-99b3bfc1a28d"),
                            Name = "Calgary Flames",
                            ShortName = "Flames",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("468b6def-be09-41f3-b86c-45eec027f4cc"),
                            Name = "Carolina Hurricanes",
                            ShortName = "Hurricanes",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a1464f78-6508-4d94-8781-11c9b8fcf722"),
                            Name = "Chicago Blackhawks",
                            ShortName = "Blackhawks",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("4745cb89-39e1-4909-976b-feba2b833165"),
                            Name = "Colorado Avalanche",
                            ShortName = "Avalanche",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("54c2f7a1-28b1-45ca-b2ba-7441259840f2"),
                            Name = "Columbus Blue Jackets",
                            ShortName = "Blue Jackets",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("6ca440a2-b726-42aa-a461-73e5e32857a3"),
                            Name = "Dallas Stars",
                            ShortName = "Stars",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("6299659a-170c-4420-856d-f3af93ccfdce"),
                            Name = "Detroit Red Wings",
                            ShortName = "Red Wings",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("17f767e0-4558-40da-a8e5-24d8ecd4a7b1"),
                            Name = "Edmonton Oilers",
                            ShortName = "Oilers",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("0bfff029-610c-4204-b798-1f1d4410e149"),
                            Name = "Florida Panthers",
                            ShortName = "Panthers",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("424dd7bf-4e38-4d44-83e1-2750e16fc0d8"),
                            Name = "Los Angeles Kings",
                            ShortName = "Kings",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("28df03d3-b656-4b70-9a4e-353672d1d601"),
                            Name = "Minnesota Wild",
                            ShortName = "Wild",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8beace9c-fed4-45f7-bcd4-bf3fe14f522c"),
                            Name = "Montreal Canadiens",
                            ShortName = "Canadiens",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("92e98e53-b5cd-4085-990f-1fa1a0fccefa"),
                            Name = "Nashville Predators",
                            ShortName = "Predators",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("006f5b08-ec66-4f56-b902-15a2425e19a1"),
                            Name = "New Jersey Devils",
                            ShortName = "Devils",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("23b2b2e8-0491-426b-aa58-e24be766a238"),
                            Name = "New York Islanders",
                            ShortName = "Islanders",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("3eec1694-fe79-47a8-996d-44cdde62542f"),
                            Name = "New York Rangers",
                            ShortName = "Rangers",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("2bf4aef5-6341-46e4-a257-7b7cb1db1c34"),
                            Name = "Ottawa Senators",
                            ShortName = "Senators",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("74e45ad2-ea56-4cb8-97d8-f7928a384bfb"),
                            Name = "Philadelphia Flyers",
                            ShortName = "Flyers",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f3c00ebd-61c5-4b42-a5f9-94b46b16165d"),
                            Name = "Pittsburgh Penguins",
                            ShortName = "Penguins",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("fe7232b4-f01c-452b-b42c-7cd8478df768"),
                            Name = "San Jose Sharks",
                            ShortName = "Sharks",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("4902b18b-e630-43c6-87c3-1370593797e5"),
                            Name = "Seattle Kraken",
                            ShortName = "Kraken",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("09f6fd9b-50dd-4fe3-b639-49a15316d080"),
                            Name = "St. Louis Blues",
                            ShortName = "Blues",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a8555359-6b1f-4785-b149-5e073df4a253"),
                            Name = "Tampa Bay Lightning",
                            ShortName = "Lightning",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8351c7ab-5bc4-4d40-991f-696f523ee587"),
                            Name = "Toronto Maple Leafs",
                            ShortName = "Maple Leafs",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ae3193c9-8ab2-4591-b80e-f98dcab9e489"),
                            Name = "Vancouver Canucks",
                            ShortName = "Canucks",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("3414e7a8-378b-495f-b481-004a8aa645a3"),
                            Name = "Vegas Golden Knights",
                            ShortName = "Golden Knights",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("352b3da6-94c4-413f-8029-c8c34834db3e"),
                            Name = "Washington Capitals",
                            ShortName = "Capitals",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("597ba0e7-3097-4e34-8e6b-80d9b2c5b9c6"),
                            Name = "Winnipeg Jets",
                            ShortName = "Jets",
                            Tags = "[\"nhl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a12932c2-459f-4886-821f-63ac5803726b"),
                            Name = "Abbotsford Canucks",
                            ShortName = "Canucks",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c55ce002-3a30-454c-bbba-039ba8baef29"),
                            Name = "Bakersfield Condors",
                            ShortName = "Condors",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("43c2517f-7900-49a2-8edc-623e223b5361"),
                            Name = "Belleville Senators",
                            ShortName = "Senators",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ee35f5dd-3dde-47b0-becf-6333ea259c89"),
                            Name = "Bridgeport Islanders",
                            ShortName = "Islanders",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("89a261e3-d987-4590-87fa-c0e7f46adc2f"),
                            Name = "Charlotte Checkers",
                            ShortName = "Checkers",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b3cc788f-5c54-4c4b-9fc2-95749ed4913d"),
                            Name = "Chicago Wolves",
                            ShortName = "Wolves",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("865dc29c-6b17-4497-9765-492382b905b3"),
                            Name = "Cleveland Monsters",
                            ShortName = "Monsters",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8ec0071f-209c-4430-ae52-8bb05b4ef403"),
                            Name = "Coachella Valley Firebirds",
                            ShortName = "Firebirds",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b8322bf8-a93d-4d84-9cee-4682d54f8f97"),
                            Name = "Colorado Eagles",
                            ShortName = "Eagles",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("80ae8034-d663-4394-809a-09f091447b09"),
                            Name = "Grand Rapids Griffins",
                            ShortName = "Griffins",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("4de59986-489b-4f51-95e9-8e7c8266d7ac"),
                            Name = "Hartford Wolf Pack",
                            ShortName = "Wolf Pack",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("9c7481d2-9d15-412d-9b4e-68b03cd9e62b"),
                            Name = "Henderson Silver Knights",
                            ShortName = "Silver Knights",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("511f0e1c-4a95-44ed-81f5-c86ec1708960"),
                            Name = "Hershey Bears",
                            ShortName = "Bears",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("75d52ec1-8b80-4a42-9962-6fba06029d1c"),
                            Name = "Iowa Wild",
                            ShortName = "Wild",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("896b1080-1eb6-48ef-8e74-404594701c2f"),
                            Name = "Laval Rocket",
                            ShortName = "Rocket",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f62728f5-10a7-4741-9312-9619585a3a40"),
                            Name = "Lehigh Valley Phantoms",
                            ShortName = "Phantoms",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a3621627-eecc-42c5-8150-b553672ded27"),
                            Name = "Manitoba Moose",
                            ShortName = "Moose",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f49f3a2a-185a-413d-a5d1-a1688a697278"),
                            Name = "Milwaukee Admirals",
                            ShortName = "Admirals",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("fdf4b0fc-7205-4f55-abfc-f3be840596af"),
                            Name = "Ontario Reign",
                            ShortName = "Reign",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("5551b8e1-700b-450c-9f44-f29209763b13"),
                            Name = "Providence Bruins",
                            ShortName = "Bruins",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("90cd276e-8445-4e36-a9e2-2a3c0355f196"),
                            Name = "Rochester Americans",
                            ShortName = "Americans",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("fd263adb-51c0-4cc9-ba04-cecf45cc291c"),
                            Name = "Rockford IceHogs",
                            ShortName = "IceHogs",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("4ce0628a-948a-4bb5-ba7f-bb825730433a"),
                            Name = "San Antonio Rampage",
                            ShortName = "Rampage",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("7c6db8a5-5b6d-4af2-bdab-33b254d37d98"),
                            Name = "San Diego Gulls",
                            ShortName = "Gulls",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("83b2f888-0080-4b73-8b9e-5accd632f618"),
                            Name = "San Jose Barracuda",
                            ShortName = "Barracuda",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("bf0ee353-28c4-47c2-9a60-8538e845a317"),
                            Name = "Springfield Thunderbirds",
                            ShortName = "Thunderbirds",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d290cd28-178a-4dcc-9813-954247e9b4e2"),
                            Name = "Stockton Heat",
                            ShortName = "Heat",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("e797189d-38ab-4b0e-bc77-0b8606ae1eeb"),
                            Name = "Syracuse Crunch",
                            ShortName = "Crunch",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ff8968a2-0895-4b0c-a28d-fb3dff7d2b2d"),
                            Name = "Texas Stars",
                            ShortName = "Stars",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a6d77b28-524a-4317-8694-076086307680"),
                            Name = "Toronto Marlies",
                            ShortName = "Marlies",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("2dd56d87-a8ec-4ea8-b883-6a90ff858a25"),
                            Name = "Tucson Roadrunners",
                            ShortName = "Roadrunners",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8ffb943c-c7c9-430a-a1af-ba6a5606e96e"),
                            Name = "Utica Comets",
                            ShortName = "Comets",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("7a457408-ade3-4cdf-865b-e2144bfb8b44"),
                            Name = "Wilkes-Barre/Scranton Penguins",
                            ShortName = "Penguins",
                            Tags = "[\"ahl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("6ac9e6a0-c4d6-4d8e-864e-4a4dd2e3917a"),
                            Name = "Acadie-Bathurst Titan",
                            ShortName = "Titan",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("4fc86f23-26b9-477c-811c-219a11abc3a9"),
                            Name = "Baie-Comeau Drakkar",
                            ShortName = "Brakkar",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("87a32ee3-bacb-4bb0-9a82-df1c6b25d0ea"),
                            Name = "Barrie Colts",
                            ShortName = "Colts",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f69d0075-2036-49d9-9059-05e94d8adcd6"),
                            Name = "Blainville-Boisbriand Armada",
                            ShortName = "Armada",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("18518127-7ce5-4c65-aeda-b9afa67a101d"),
                            Name = "Brandon Wheat Kings",
                            ShortName = "Wheat Kings",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("149a27a9-a3f0-4f56-a1fd-b37d2f4a6915"),
                            Name = "Calgary Hitmen",
                            ShortName = "Hitmen",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b2286c1d-d71c-4114-9ba0-cded81a12035"),
                            Name = "Cape Breton Screaming Eagles",
                            ShortName = "Screaming Eagles",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8e054ad9-2892-41d2-a648-4ca6a2ef2d04"),
                            Name = "Charlottetown Islanders",
                            ShortName = "Islanders",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("5b158251-1a3e-40ef-8a5a-d9e6cbd146b1"),
                            Name = "Chicoutimi Sagueneens",
                            ShortName = "Sagueneens",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("7d8c67df-1c02-46aa-a263-a950fe3aeef0"),
                            Name = "Drummondville Voltigeurs",
                            ShortName = "Voltigeurs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d45a0944-9fd7-4786-9a09-800fbdeb8a53"),
                            Name = "Edmonton Oil Kings",
                            ShortName = "Oil Kings",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ddc83d01-a516-4dfa-bf30-4db388a2decb"),
                            Name = "Erie Otters",
                            ShortName = "Otters",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("63dd296b-55d9-4da3-8207-d2444f20ed4a"),
                            Name = "Everett Silvertips",
                            ShortName = "Silvertips",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c85f679e-2f97-47c6-9334-e484ae827396"),
                            Name = "Flint Firebirds",
                            ShortName = "Firebirds",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d47636d9-d3fc-492a-bf29-8d0c9eb85283"),
                            Name = "Gatineau Olympiques",
                            ShortName = "Olympiques",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8a0bb7dd-8f8c-475c-a47f-95836b613983"),
                            Name = "Guelph Storm",
                            ShortName = "Storm",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d167f677-cda1-461a-b49b-7050b7fda4c5"),
                            Name = "Halifax Mooseheads",
                            ShortName = "Mooseheads",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("a5cad9c3-a407-41d6-a0a0-387def7408bf"),
                            Name = "Hamilton Bulldogs",
                            ShortName = "Bulldogs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("74037536-7225-4d5b-bb11-7079fb404ff2"),
                            Name = "Kamloops Blazers",
                            ShortName = "Blazers",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("6da73452-a860-495a-b987-0d8fce00ef1e"),
                            Name = "Kelowna Rockets",
                            ShortName = "Rockets",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("24bf4f45-9e6e-4265-8d84-19c1e61ebbee"),
                            Name = "Kingston Frontenacs",
                            ShortName = "Frontenacs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("fe315ea4-6bcf-49b4-b632-03fae03e4e20"),
                            Name = "Kitchener Rangers",
                            ShortName = "Rangers",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("52880339-641a-4fbd-a5f2-b1d1e615b0c7"),
                            Name = "Kootenay Ice",
                            ShortName = "Ice",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("28533059-5482-4619-95fc-886d414bb877"),
                            Name = "Lethbridge Hurricanes",
                            ShortName = "Hurricanes",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("163f5dde-842d-4179-afbc-6248f5d65a49"),
                            Name = "London Knights",
                            ShortName = "Knights",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("0306f07b-4c19-4961-a47a-cc18d180d34e"),
                            Name = "Medicine Hat Tigers",
                            ShortName = "Tigers",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ab1186ac-bf60-419e-b49f-b516d8c7871e"),
                            Name = "Mississauga Steelheads",
                            ShortName = "Steelheads",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("61646327-282a-470a-bf41-7a6cd5d0569b"),
                            Name = "Moncton Wildcats",
                            ShortName = "Wildcats",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d59fa64c-1888-4bef-a19d-d8c2b2ff3bcc"),
                            Name = "Moose Jaw Warriors",
                            ShortName = "Warriors",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("596fd2e8-9814-4973-b880-0b38e2e2d850"),
                            Name = "Niagara IceDogs",
                            ShortName = "IceDogs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c5bc2260-bd0d-457c-9023-0b00c49da4e7"),
                            Name = "North Bay Battalion",
                            ShortName = "Battalion",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("ebc5cf8c-de57-4eee-a796-2638557cdd30"),
                            Name = "Oshawa Generals",
                            ShortName = "Generals",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b3dd97e5-3f0b-4e9d-bfc0-4c9dacb20f83"),
                            Name = "Ottawa 67's",
                            ShortName = "67's",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("9f5264ed-b83a-4695-b160-7f2b3bb5e255"),
                            Name = "Owen Sound Attack",
                            ShortName = "Attack",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b7d6f01b-1dea-403a-b3fe-a201e747313c"),
                            Name = "Peterborough Petes",
                            ShortName = "Petes",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b683888a-51eb-4c2c-9454-fa495d0e78ce"),
                            Name = "Portland Winterhawks",
                            ShortName = "Winterhawks",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("44bd4000-006c-4d32-9b15-ec4299ba18f5"),
                            Name = "Prince Albert Raiders",
                            ShortName = "Raiders",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f9c20cb7-7414-485a-b7f5-a014faf8b221"),
                            Name = "Prince George Cougars",
                            ShortName = "Cougars",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("8535d4c7-c465-4cb7-9973-152370ab0941"),
                            Name = "Quebec Remparts",
                            ShortName = "Remparts",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("63d33eeb-14ba-40ff-b09d-d84076485480"),
                            Name = "Red Deer Rebels",
                            ShortName = "Rebels",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c2f4699e-e4d5-4ccc-9c94-e5002733dad7"),
                            Name = "Regina Pats",
                            ShortName = "Pats",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("07f0f89d-5dd5-46c5-ba56-5d49baa5c963"),
                            Name = "Rimouski Oceanic",
                            ShortName = "Oceanic",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("20682d4f-fc2a-4d04-99a5-77f6664ccc08"),
                            Name = "Rouyn-Noranda Huskies",
                            ShortName = "Huskies",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("5f445e64-b7bf-4d79-b248-b431c541e2ba"),
                            Name = "Saginaw Spirit",
                            ShortName = "Spirit",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("928acb7f-3914-4fd3-aa64-3b9b19636eca"),
                            Name = "Saint John Sea Dogs",
                            ShortName = "Sea Dogs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("bb1b8c2b-3b67-4b3f-95a0-79c2d37710b0"),
                            Name = "Sarnia Sting",
                            ShortName = "Sting",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("1a9718d4-44df-4fe6-9375-686bc46e4de7"),
                            Name = "Saskatoon Blades",
                            ShortName = "Blades",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("80a5ca3b-94d6-462d-9c2b-68d8ff74f1c8"),
                            Name = "Sault Ste. Marie Greyhounds",
                            ShortName = "Greyhounds",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("b4c7f188-8a02-4c39-904c-70e977fdd3f4"),
                            Name = "Seattle Thunderbirds",
                            ShortName = "Thunderbirds",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("e22a1261-58ce-4ac2-a770-67aabce957bf"),
                            Name = "Shawinigan Cataractes",
                            ShortName = "Cataractes",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d24ced8c-785d-46f0-b719-bf9cddc72937"),
                            Name = "Sherbrooke Phoenix",
                            ShortName = "Phoenix",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("3dedbfb1-4c71-44fb-993d-afa3612f222f"),
                            Name = "Spokane Chiefs",
                            ShortName = "Chiefs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("08546050-4b0c-42c6-ac21-27706bc3dcb7"),
                            Name = "Sudbury Wolves",
                            ShortName = "Wolves",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("61742d85-6a7b-4b24-8bfa-48db06077bf5"),
                            Name = "Swift Current Broncos",
                            ShortName = "Broncos",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("89787e32-e720-412c-b0c0-4b44af36b2c7"),
                            Name = "Tri City Americans",
                            ShortName = "Americans",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("d5b7ea33-e2e1-4560-aebf-ed2cc940ba50"),
                            Name = "Val-d'Or Foreurs",
                            ShortName = "Foreurs",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("f2e807ba-f4d5-467e-a35b-4a57cb0013e5"),
                            Name = "Vancouver Giants",
                            ShortName = "Giants",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("21c164ab-94fa-4d5c-a772-8593e11d3368"),
                            Name = "Victoria Royals",
                            ShortName = "Royals",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("225a6082-b4d2-4b96-a50f-438a35613f57"),
                            Name = "Victoriaville Tigres",
                            ShortName = "Tigres",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("7820614b-b216-4c7a-8cd4-4b29d3836e99"),
                            Name = "Windsor Spitfires",
                            ShortName = "Spitfires",
                            Tags = "[\"chl\",\"hockey\"]"
                        },
                        new
                        {
                            Id = new Guid("c1131bef-99e7-4e5b-a012-e412e8cc5f00"),
                            Name = "Atlanta Hawks",
                            ShortName = "Hawks",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("60ab0cd0-a54b-48b9-8ec8-082029d5ba92"),
                            Name = "Boston Celtics",
                            ShortName = "Celtics",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("ece6e51f-fe5e-4d9b-9a55-cff588fada45"),
                            Name = "Brooklyn Nets",
                            ShortName = "Nets",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("281dd704-3504-4ecc-a8c3-3c7d9eeecdd1"),
                            Name = "Charlotte Hornets",
                            ShortName = "Hornets",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("e3551df5-8e2e-4a03-8d1d-3aa3a96ad2ac"),
                            Name = "Chicago Bulls",
                            ShortName = "Bulls",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("5f58a1f4-d7b5-4d57-a6dd-47b7aaf19dce"),
                            Name = "Cleveland Cavaliers",
                            ShortName = "Cavaliers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("ebfe66fb-4c49-4406-945a-075376822536"),
                            Name = "Dallas Mavericks",
                            ShortName = "Mavericks",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("dc40e0a0-9953-4770-80c9-ecfa42ee5eaf"),
                            Name = "Denver Nuggets",
                            ShortName = "Nuggets",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("ed188592-8997-42e4-81a9-ce46cdfe9cce"),
                            Name = "Detroit Pistons",
                            ShortName = "Pistons",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("6822d814-d1f4-4db9-a008-32a8d6621ed9"),
                            Name = "Golden State Warriors",
                            ShortName = "Warriors",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("19cae9b1-f408-46ed-b02d-19ef9116f036"),
                            Name = "Houston Rockets",
                            ShortName = "Rockets",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("d0cfa638-7561-4374-ba0e-c3c0baad20e6"),
                            Name = "Indiana Pacers",
                            ShortName = "Pacers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("f0db239b-8d0a-4f20-96d5-f09bf251ee58"),
                            Name = "Los Angeles Clippers",
                            ShortName = "Clippers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("7e46b1ae-4614-4823-ad9a-d26dfd291daf"),
                            Name = "Los Angeles Lakers",
                            ShortName = "Lakers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("2e4ab086-ac90-4f0d-92c2-3530b6b7745f"),
                            Name = "Memphis Grizzlies",
                            ShortName = "Grizzlies",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("11efffb9-17fd-4803-ad7d-dd17f269b400"),
                            Name = "Miami Heat",
                            ShortName = "Heat",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("47d26c47-feec-45a9-9753-341622ca00af"),
                            Name = "Milwaukee Bucks",
                            ShortName = "Bucks",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("66a99a9d-d3f2-4825-b543-1fc20d4142b6"),
                            Name = "Minnesota Timberwolves",
                            ShortName = "Timberwolves",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("bcd0f97b-07a8-4fac-853d-2324f1b959ff"),
                            Name = "New Orleans Pelicans",
                            ShortName = "Pelicans",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("86027d33-0d79-4b8c-9a2c-a8a9c1b86c25"),
                            Name = "New York Knicks",
                            ShortName = "Knicks",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("77dc17e2-89ac-4092-ba13-7005adf6335e"),
                            Name = "Oklahoma City Thunder",
                            ShortName = "Thunder",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("02da4cf8-bfd5-4bd1-8c28-8bcaf27910f4"),
                            Name = "Orlando Magic",
                            ShortName = "Magic",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("4c92af9b-b9ee-4e50-866c-55682516f9c4"),
                            Name = "Philadelphia 76ers",
                            ShortName = "76ers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("da45a77b-a05e-4b63-92fa-46e7cd72cc7a"),
                            Name = "Phoenix Suns",
                            ShortName = "Suns",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("a82a334e-dcea-47f7-83d8-be53817fce96"),
                            Name = "Portland Trail Blazers",
                            ShortName = "Trail Blazers",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("92bdd5df-5b5f-48d9-8f75-5385608b03c4"),
                            Name = "Sacramento Kings",
                            ShortName = "Kings",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("862a6dcf-5453-4ace-b6a3-b9cd9f573cf7"),
                            Name = "San Antonio Spurs",
                            ShortName = "Spurs",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("bc2f3ae4-3031-4693-ac56-3602546cd840"),
                            Name = "Toronto Raptors",
                            ShortName = "Raptors",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("d44a5871-60c8-4d61-8634-b3fa5fb64a0b"),
                            Name = "Utah Jazz",
                            ShortName = "Jazz",
                            Tags = "[\"nba\",\"basketball\"]"
                        },
                        new
                        {
                            Id = new Guid("02e4284b-223f-45f2-9211-260a7227fe4d"),
                            Name = "Washington Wizards",
                            ShortName = "Wizards",
                            Tags = "[\"nba\",\"basketball\"]"
                        });
                });

            modelBuilder.Entity("Duthie.Types.Watchers.Watcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GuildId", "LeagueId", "TeamId", "Type", "ChannelId")
                        .IsUnique();

                    b.ToTable("Watchers", (string)null);
                });

            modelBuilder.Entity("Duthie.Types.Games.Game", b =>
                {
                    b.HasOne("Duthie.Types.Teams.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("Duthie.Types.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duthie.Types.Teams.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("Duthie.Types.GuildAdmin", b =>
                {
                    b.HasOne("Duthie.Types.Guilds.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Duthie.Types.GuildMessage", b =>
                {
                    b.HasOne("Duthie.Types.Guilds.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Duthie.Types.Leagues.League", b =>
                {
                    b.HasOne("Duthie.Types.Sites.Site", "Site")
                        .WithMany("Leagues")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Duthie.Types.Leagues.LeagueTeam", b =>
                {
                    b.HasOne("Duthie.Types.Leagues.League", "League")
                        .WithMany("LeagueTeams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duthie.Types.Teams.Team", "Team")
                        .WithMany("LeagueTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Duthie.Types.Watchers.Watcher", b =>
                {
                    b.HasOne("Duthie.Types.Guilds.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duthie.Types.Leagues.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duthie.Types.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Duthie.Types.Leagues.League", b =>
                {
                    b.Navigation("LeagueTeams");
                });

            modelBuilder.Entity("Duthie.Types.Sites.Site", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("Duthie.Types.Teams.Team", b =>
                {
                    b.Navigation("LeagueTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
